/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include"FreeRTOSConfig.h"
#include"FreeRTOS.h"
#include"task.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vMainTaskFunction(void * pvParam)
{
	while(1){
		// work
		vTask1();
		vTaskDelay(1000/portTICK_RATE_MS);

		vTask2();
		vTaskDelay(1000/portTICK_RATE_MS);

		vTask3();
		vTaskDelay(1000/portTICK_RATE_MS);

		vTask4();
		vTaskDelay(1000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
void vTask1( void *pvParameters ){


	while(1){
		// work
		led_toggle(LED_GREEN);
		vTaskDelay(1000/portTICK_RATE_MS);
		vTaskDelete(NULL);

	}
}
void vTask2( void *pvParameters ){


	while(1){

		led_toggle(LED_ORANGE);
		vTaskDelay(1000/portTICK_RATE_MS);
		vTaskDelete(NULL);

	}
}

void vTask3( void *pvParameters ){

	while(1){
		// work

		led_toggle(LED_RED);
		vTaskDelay(1000/portTICK_RATE_MS);
		vTaskDelete(NULL);
	}
}
void vTask4( void *pvParameters ){

	while(1){
		// work

		led_toggle(LED_BLUE);
		vTaskDelay(1000/portTICK_RATE_MS);
		vTaskDelete(NULL);
	}
}
int main(void)
{
		led_init(LED_GREEN);
		led_init(LED_ORANGE);
		led_init(LED_RED);
		led_init(LED_BLUE);


		xTaskCreate(vTask1, "vTask1", configMINIMAL_STACK_SIZE, NULL, 1, NULL);
		xTaskCreate(vTask2, "vTask2", configMINIMAL_STACK_SIZE, NULL, 2, NULL);
		xTaskCreate(vTask3, "vTask3", configMINIMAL_STACK_SIZE, NULL, 3, NULL);
		xTaskCreate(vTask4, "vTask4", configMINIMAL_STACK_SIZE, NULL, 4, NULL);

	vTaskStartScheduler();
	while(1);
}














